"""Layer-neutral contracts shared across glossa."""

from .contracts import (
    AttributeFact,
    Diagnostic,
    DocstringEdit,
    EditKind,
    ExceptionFact,
    ExtractedDocstring,
    ExtractedTarget,
    FixPlan,
    LintTarget,
    ModuleSymbolFact,
    ParameterFact,
    RelatedTargetSnapshot,
    RelatedTargets,
    ResolvedRelatedTargets,
    RulePolicy,
    Severity,
    SignatureFacts,
    SourceRef,
    TargetKind,
    TextPosition,
    TextSpan,
    Visibility,
    WarningFact,
)

__all__ = [
    "AttributeFact",
    "Diagnostic",
    "DocstringEdit",
    "EditKind",
    "ExceptionFact",
    "ExtractedDocstring",
    "ExtractedTarget",
    "FixPlan",
    "LintTarget",
    "ModuleSymbolFact",
    "ParameterFact",
    "RelatedTargetSnapshot",
    "RelatedTargets",
    "ResolvedRelatedTargets",
    "RulePolicy",
    "Severity",
    "SignatureFacts",
    "SourceRef",
    "TargetKind",
    "TextPosition",
    "TextSpan",
    "Visibility",
    "WarningFact",
]
